services:
  pgserver:
    container_name: pgserver
    image: postgres
    networks:
      - network-1
    ports:
      - "5555:5432"
    volumes:
      - d:\tmp\docker-backend\data:/var/lib/postgresql/data
      - d:\tmp\docker-backend\sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  springboot-docker:
    container_name: springboot-docker
    #build: ./
    image: backend-docker
    networks:
      - network-1
    ports:
      - "8080:8080"
    depends_on:
      pgserver:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgserver:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
networks:
  network-1:
